### PR TITLE
Fix const disjoint

### LINKED ISSUE #985: disjoint does not work for const points
A disjoint of two geometries of which both points are const (or one of them) does not work, because internally those point types are used to calculate turns

### PR DESCRIPTION
**Pull request by barendgehrels**
Fixes #985 

Some pieces of the touched code become a bit simpler by this (for example avoiding an extra conversion).

There are some renamings as well, such as `get_turns` (this was really inconvenient, there is a namespace and a free function as well - and this does something different - so I call it `turn_retriever` now) and `define_turn_operation_type` i/o `turn_operation_type` (because that is there as well).

Also there are some white space changes (at end of lines), fixed by my editor.

### CODE REVIEW

File: include/boost/geometry/algorithms/detail/sections/section_functions.hpp [hunk 1]
```diff
@@ -148,11 +149,11 @@ template
     typename Box,
     typename RobustPolicy
 >
-static inline bool exceeding(int dir,
-                             Point const& point,
-                             Box const& point_box,
-                             Box const& other_box,
-                             RobustPolicy const& robust_policy)
+inline bool exceeding(int dir,
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/detail/sections/section_functions.hpp:152]: These two are unrelated but should not be declared as `static`

File: test/algorithms/relate/relate_const.cpp [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+    namespace bg = boost::geometry;
+
+    BOOST_CHECK_EQUAL(exp_cov, bg::covered_by(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_crosses, bg::crosses(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_disjoint, bg::disjoint(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_intersects, bg::intersects(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_overlaps, bg::overlaps(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_touches, bg::touches(geometry1, geometry2));
+    BOOST_CHECK_EQUAL(exp_relate, bg::relate(geometry1, geometry2, bg::de9im::mask("F0F******")));
+    BOOST_CHECK_EQUAL(exp_within, bg::within(geometry1, geometry2));
```
Comment (barendgehrels) [inline test/algorithms/relate/relate_const.cpp:39]: So it fixes not only disjoint, but many boolean relation operators

File: include/boost/geometry/algorithms/detail/overlay/get_turns.hpp [hunk 3]
```diff
@@ -926,24 +926,24 @@ struct get_turn_info_type<Geometry1, Geometry2, AssignPolicy, Tag1, Tag2, linear
     : overlay::get_turn_info_linear_areal<AssignPolicy>
 {};
 
-template <typename Geometry1, typename Geometry2, typename SegmentRatio,
+template <typename Geometry1, typename Geometry2, typename Point, typename SegmentRatio,
           typename Tag1 = typename tag<Geometry1>::type, typename Tag2 = typename tag<Geometry2>::type,
           typename TagBase1 = typename topological_tag_base<Geometry1>::type, typename TagBase2 = typename topological_tag_base<Geometry2>::type>
-struct turn_operation_type
+struct define_turn_operation_type
```
Comment (awulkiew) [inline include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:932]: What is the reasoning behind this change? Verbs are typically used for functions or metafunctions semantically modifying a type. Consider that `point_type` is not named `define_point_type`.

File: include/boost/geometry/algorithms/detail/relate/turns.hpp [hunk 4]
```diff
@@ -40,21 +40,20 @@ struct assign_policy
...
     typename Geometry1,
     typename Geometry2,
+    typename Point,
     typename GetTurnPolicy = detail::get_turns::get_turn_info_type
         <
             Geometry1, Geometry2, assign_policy<>
         >
 >
-struct get_turns
+struct turn_retriever
```
Comment (awulkiew) [inline include/boost/geometry/algorithms/detail/relate/turns.hpp:55]: Why was this name changed? What was the original problem? That it's confused with the original `get_turns`?

Anyway this is semantically not a class which object is created somewhere like a functor/predicate whatever (it's not a retriever created and used somewhere) but implementation of an algorithm with static member function `apply()`. We use verbs for these in the library right?

BTW, if I was implementing this now it'd be free function `detail::relate::get_turns()`.

**Comment by awulkiew** [comment]
It looks good to me in general but you mixed fixing the "const" issue with renaming of interfaces. This is out of scope of this PR potentially interferes with my work on the support of GCs in relops (I haven't checked how much). Not to mention I think the names are incorrect as I mentioned in the comments.

I also don't understand the confusion. `turns::get_turns::apply()` calls `get_turns` algorithm with some of the parameters defined. Would it be more intuitive for you if it was a free function `relate::get_turns()`?

File: include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp [hunk 5]
```diff
@@ -94,42 +98,33 @@ class boundary_checker<Geometry, Strategy, multi_linestring_tag>
...
 
         if ( ! m_is_filled )
         {
             //boundary_points.clear();
             m_boundary_points.reserve(multi_count * 2);
 
-            typedef typename boost::range_iterator<Geometry const>::type multi_iterator;
-            for ( multi_iterator it = boost::begin(m_geometry) ;
-                  it != boost::end(m_geometry) ; ++ it )
+            for (auto const& ls : m_geometry)
```
Comment (awulkiew) [inline include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp:118]: This is incorrect. MultiLinestring has to be Boost.Range not STD range.

In general we cannot use range based for loop for a geometry that can be passed by the user, only for geometries and containers that we create ourselves internally.

File: include/boost/geometry/algorithms/detail/relate/linear_areal.hpp [hunk 6]
```diff
@@ -1299,9 +1289,21 @@ struct linear_areal
...
+        bool calculate_from_inside_sides(Pi const& pi, Pj const& pj, Pk const& pk,
+                                         Qi const& qi, Qj const& qj, Qk const& qk,
+                                         Strategy const& strategy)
         {
+            la_side_calculator
+            <
+                Strategy,
+                Pi, Pj, Pk,
+                Qi, Qj, Qk
+            > side_calc(pi, pj, pk, qi, qj, qk, strategy);
```
Comment (awulkiew) [inline include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:1305]: If that's the preferred way then I suggest to remove `la_side_calculator` entirely and replace function calls like `pk_wrt_p()` with corresponding strategy calls.

File: include/boost/geometry/algorithms/detail/relate/linear_areal.hpp [hunk 7]
```diff
@@ -1255,21 +1252,14 @@ struct linear_areal
...
             {
-                point2_type new_qj;
-                geometry::convert(turn.point, new_qj);
-
-                la_side_calculator<cs_tag, point1_type, point2_type, Strategy>
-                    side_calc(qi_conv, new_pj, pi, qi, new_qj, qj, strategy);
-
-                return calculate_from_inside_sides(side_calc);
+                // Calculate sides with different points for P and Q
+                return calculate_from_inside_sides(qi, turn.point, pi, qi, turn.point, qj, strategy);
```
Comment (awulkiew) [inline include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:1262]: AFAIR the conversion was done because sometimes point type of one geometry is used to create a segment with the point type of another geometry. But AFAIS side strategies are able to take three different points so I think it should work but is it tested?

**Comment by awulkiew** [comment]
As I mentioned in one of the previous PRs related to const points this issue is confusing to me. I'd like to do some testing myself because I didn't get an answer then. I suspect that the cause of this issue is somewhere else. The changes made in this PR should be irrelevant.

Furthermore this is not about const points but about points defining only `get()`. You test point can be assigned to, it defines copy ctor and assignment operator, etc. It's not about copying. It is possible to copy it or store in a container. You couldn't use it in a linestring if it was otherwise.

There is also a separate issue which is that your test point doesn't define default ctor. This also has nothing to do with constness. It's a different issue.

File: include/boost/geometry/algorithms/detail/relate/turns.hpp (hunk 4 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/turns.hpp:55]: See the PR's description: `get_turns` is a free function which does something else.

**Comment by barendgehrels** [comment]
> It looks good to me in general but you mixed fixing the "const" issue with renaming of interfaces. This is out of scope of this PR potentially interferes with my work on the support of GCs in relops (I haven't checked how much). Not to mention I think the names are incorrect as I mentioned in the comments.
> 

Yes, I could have split it - but then you would see a name change and right after a PR with a contents change. I thought there was no problem in one go for lines touched anyway.

I don't think it will interfere (a lot), this is not specific for any geometry type. Apart from that: with splitted PR's it interfers even more.

File: include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp (hunk 5 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp:118]: All right I will revert this. Thanks.

File: include/boost/geometry/algorithms/detail/relate/linear_areal.hpp (hunk 6 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:1305]: I don't want to make the PR bigger. I don't say it's the preferred way - it is a more convenient way than before, because it does not need conversions.

File: include/boost/geometry/algorithms/detail/relate/linear_areal.hpp (hunk 7 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:1262]: Yes, side strategies should take three different point types.

**Comment by barendgehrels** [comment]
> 

I answered your point in the previous PR. See the file `const_point.hpp` defining such a point type, and indeed: with no setters and no default constructor. It's exactly this type that I encountered in practice. And you could implement first one (with default constructor) and then this one (without default constructor) but what's the point... It touches nearly the same code.

Maybe the name is not perfect, I mean a point type which no setters and no default constructor (effectively it can't be changed after construction, therefore a `const_point` is not that bad. It is a `non_mutable_point`

File: include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp (hunk 5 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/boundary_checker.hpp]: :heavy_check_mark:

File: include/boost/geometry/algorithms/detail/overlay/get_turns.hpp (hunk 3 above)
Comment (awulkiew) [reply include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:932]: What different `turn_operation_type` are you talking about? I tried to find it but I only see typedefs. AFAIU this is the only `struct` of this name. So if my understanding is correct this is the same case as it is with `geometry::point_type<>::type` and `typedef ... point_type`. Or am I missing something?

File: include/boost/geometry/algorithms/detail/relate/linear_areal.hpp (hunk 6 above)
Comment (awulkiew) [reply include/boost/geometry/algorithms/detail/relate/linear_areal.hpp:1305]: Ok got it.

File: include/boost/geometry/algorithms/detail/relate/turns.hpp (hunk 4 above)
Comment (awulkiew) [reply include/boost/geometry/algorithms/detail/relate/turns.hpp:55]: Yes, `geometry::get_turns()` is a free function, `dispatch::get_turns` is a struct and `detail::get_turns_generic` is a struct as well (the implementation). `detail::relate::turns::get_turns` is an implementation as well. The only difference between `geometry::get_turns()` and `relate::turns::get_turns::apply()` is that parameters common across all relops and L/L setops are set here internally so the caller is not forced to pass them each time the same way. As I mentioned it could as well be implemented as a free function. It's neither a retriever nor a getter it's an implementation of an algorithm `get_turns()` specific for relops.

**Comment by awulkiew** [comment]
I get your point now. So there are several issues addressed by your recent PRs which may be confusing:
1. support for point types defining only getters
2. support for point types without default constructor
3. refactoring

1 and 2 are often used together in the library because of the semantics of some utilities used in the library, e.g. `point_on_border` or `envelope` which requires to create an object with default ctor and then to set the coordinates. So it indeed makes sense to address these issues together.

I'd only refrain from doing refatoring at the same time because this would limit the scope of the PR. E.g. now instead of simply talking about the important issues 1 and 2 we have to also talk about naming etc.

File: include/boost/geometry/algorithms/detail/overlay/get_turns.hpp (hunk 3 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/overlay/get_turns.hpp:932]: Yes, it’s probably the only struct indeed. All right, I will rename it back, it’s easier than it was to make it unique.

File: include/boost/geometry/algorithms/detail/relate/turns.hpp (hunk 4 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/relate/turns.hpp:55]: I will also rename this back.

**Comment by barendgehrels** [comment]
> I get your point now. So there are several issues addressed by your recent PRs which may be confusing:
> 
> 1. support for point types defining only getters
> 2. support for point types without default constructor
> 3. refactoring
> 
> 1 and 2 are often used together in the library because of the semantics of some utilities used in the library, e.g. `point_on_border` or `envelope` which requires to create an object with default ctor and then to set the coordinates. So it indeed makes sense to address these issues together.
> 
> I'd only refrain from doing refatoring at the same time because this would limit the scope of the PR. E.g. now instead of simply talking about the important issues 1 and 2 we have to also talk about naming etc.

Thank you. So we go for 1 and 2. About 3: I understand and will rename it back. And I will not create a follow-up, because apparently the new names are not so easy to choose, so it’s fine then. It was still useful for me in the process of adding the extra template parameter(s) there.

**Comment by barendgehrels** [comment]
:heavy_check_mark: renamed back go `turn_operation_type` and `get_turns`

**Review by awulkiew — APPROVED** [review]

**Comment by awulkiew** [comment]
Thanks for the fix and the discussion!

Btw, would you be ok with changing `struct get_turns` to free function `detail::relate::get_turns()`? Would it be more intuitive or would you still prefer a different name to distinguish it from `geometry::get_turns()`?

**Comment by barendgehrels** [comment]
> Thanks for the fix and the discussion!
> 
> Btw, would you be ok with changing `struct get_turns` to free function `detail::relate::get_turns()`? Would it be more intuitive or would you still prefer a different name to distinguish it from `geometry::get_turns()`?

Actually the names are fine, you convinced me. ;-)

A free function would be fine too, for me, unless it will depend on SFINAE.

**Comment by vissarion** [comment]
Sorry I was super late here! It look ok to me, though. Thanks!
