### PR TITLE
Fix/issue #1326 and #1226

### LINKED ISSUE #1226: union_ returns invalid polygon
This code simply takes the union of two simple polygons. But with these specific polygons the result is a "double wound" polygon, i.e. the path goes around the rim twice. Fails with 1.83 and 1.84, but works with 1.73, but that might just be due to that version not running with BOOST_GEOMETRY_NO_ROBUSTNESS.
```
#include <boost/geometry.hpp>
#include <boost/geometry/geometries/polygon.hpp>
#include <boost/geometry/geometries/adapted/boost_tuple.hpp>
BOOST_GEOMETRY_REGISTER_BOOST_TUPLE_CS(cs::cartesian)
#include <iostream>

typedef boost::tuple<double, double> point;
typedef boost::geometry::model::polygon<point> polygon;

int main() {
    polygon a{{
        {-0.90478776881879274807, .51756843862589896332},
        {-0.91, .48},
        {-1.2, .4},
        {-1.4, 1.9},
        {-0.90478776881879274807, .51756843862589896332},
    }};
    polygon b{{
        {-0.91943242964602156508, .55292377741135378955},
        {-0.90478776881879174887, .51756843862590162786},
        {-0.91, .48},
    }};
    std::vector<polygon> output;
    boost::geometry::union_(a, b, output);

    std::cout << "a: " << boost::geometry::to_wkt(a) << "\n";
    std::cout << "b: " << boost::geometry::to_wkt(b) << "\n";
    for (const auto& pg : output)
        std::cout << "output: " << boost::geometry::to_wkt(pg) << "\n";
}
```
Can be compiled on windows with:
````
cl test.cpp /EHsc /O2 -std:c++17 /Fe:test.exe -I ..\boost_1.84\boost\include
````
And running the executable result in:
```
a: POLYGON((-0.904788 0.517568,-0.91 0.48,-1.2 0.4,-1.4 1.9,-0.904788 0.517568))
b: POLYGON((-0.919432 0.552924,-0.904788 0.517568,-0.91 0.48,-0.919432 0.552924))
output: POLYGON((-0.91 0.48,-1.2 0.4,-1.4 1.9,-0.904788 0.517568,-0.904788 0.517568,
                 -0.91 0.48,-1.2 0.4,-1.4 1.9,-0.904788 0.517568,-0.91 0.48))
```
Note that polygon a has 5 points (including closing duplicate), polygon b has 4 points, but output has 10 and I don't think the output should ever have more points than the sum of the input polygons. And going around twice seems to me to be invalid.

### PR DESCRIPTION
**Pull request by barendgehrels**
This could occur in a sequence of touch and then touch_interior.
This PR fixes #1226 and #1326

### CODE REVIEW

File: include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp [hunk 1]
```diff
@@ -88,72 +88,155 @@ inline bool corresponding_turn(Turn const& turn, Turn const& start_turn,
...
 }
 
+//  Verify turns (other than start, and cross) if they are present in the map, and if so,
+//  if they have the other turns as corresponding, discard the start turn.
+template <typename Turns, typename TurnBySegmentMap, typename Geometry0, typename Geometry1>
+void discard_duplicate_start_turns(Turns& turns,
+                                   TurnBySegmentMap const& start_turns_by_segment,
+                                   Geometry0 const& geometry0,
+                                   Geometry1 const& geometry1)
+{
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp:98]: This function is not new, but it is extracted from the original method below

File: include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp [hunk 2]
```diff
@@ -88,72 +88,155 @@ inline bool corresponding_turn(Turn const& turn, Turn const& start_turn,
...
+//  - they are consecutive
+//  - the first has a touch, the second a touch_interior
+// And then one of the segments touches the others next in the middle.
+// This is geometrically not possible, and caused by floating point precision.
+// Discard the second (touch interior)
+template <typename Turns, typename Geometry0, typename Geometry1>
+void discard_touch_touch_interior_turns(Turns& turns,
+                                        Geometry0 const& geometry0,
+                                        Geometry1 const& geometry1)
+{
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp:142]: This is the fix

File: doc/release_notes.qbk [hunk 3]
```diff
@@ -19,6 +19,20 @@
 
 [section:release_notes Release Notes]
 
+[/=================]
+[heading Boost 1.87]
+[/=================]
```
Comment (barendgehrels) [inline doc/release_notes.qbk:24]: If it does not make it to 1.88, we'll update

File: test/algorithms/set_operations/difference/difference.cpp [hunk 4]
```diff
@@ -613,6 +613,13 @@ void test_all()
 
     TEST_DIFFERENCE(issue_1138, 1, 203161.751, 2, 1237551.0171, 1);
 
+    {
+        ut_settings settings;
+        settings.set_test_validity(false);
+        settings.validity_of_sym = false;
+        TEST_DIFFERENCE_WITH(issue_1226, 1, 0.238037722, 0, 0.0, 1, settings);
```
Comment (barendgehrels) [inline test/algorithms/set_operations/difference/difference.cpp:620]: Somehow they are reported as invalid.
While (I test in `overlay.cpp`) in the original test code, they were valid. 
I don't know the reason, it might be a false negative or a ccw issue

File: include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp [hunk 5]
```diff
@@ -88,72 +88,154 @@ inline bool corresponding_turn(Turn const& turn, Turn const& start_turn,
...
+
+            // Compare 0 with 0 and 1 with 1
+            // Note that 0 has always source 0 and 1 has always source 1
+            // (not in buffer). Therefore this comparison is OK.
+            // MAYBE we need to check for buffer.
+            bool const common0 = current_turn.operations[0].seg_id == previous_turn.operations[0].seg_id;
+            bool const common1 = current_turn.operations[1].seg_id == previous_turn.operations[1].seg_id;
+
+            // If one of the operations is common, and the other is not, then there is one comment segment.
+            bool const has_common_segment = common0 != common1;
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp:164]: I’ll adapt it slightly tomorrow.
Also this change somehow introduces a dependency.
```
gcc.compile.c++ bin.v2/libs/geometry/test/headers/h-algorithms-detail-overlay-discard_duplicate_turns.test/gcc-11/debug/x86_64/threading-multi/visibility-hidden/h-algorithms-detail-overlay-discard_duplicate_turns.o
```

File: include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp [hunk 6]
```diff
@@ -88,72 +88,154 @@ inline bool corresponding_turn(Turn const& turn, Turn const& start_turn,
...
     };
 
-    // 1 Build map of start turns (multi/ring-id -> turn indices)
-    std::map<multi_and_ring_id_type, std::vector<std::size_t>> start_turns_per_segment;
-    std::size_t index = 0;
     for (auto const& turn : turns)
     {
-        if (turn.method == method_start)
+        // Any turn which "crosses" does not have a corresponding turn.
+        // Also avoid comparing "start" with itself, or with touch/touch_interior
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp:108]: I added this in the comment but later changed it. I’ll remove the touch part again.

**Review by vissarion — APPROVED** [review]
Looks good to me, thanks for the fixes!

File: doc/release_notes.qbk (hunk 3 above)
Comment (barendgehrels) [reply doc/release_notes.qbk:24]: ✅

File: include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp [hunk 7]
```diff
@@ -88,72 +88,154 @@ inline bool corresponding_turn(Turn const& turn, Turn const& start_turn,
...
+            map[adapt_id(op.seg_id)].insert(index);
+        }
+    };
+
+    // Build map of start turns (multi/ring-id -> turn indices)
+    // and count touch and touch_interior turns (to verify if later checks are needed)
+    std::map<multi_and_ring_id_type, std::set<std::size_t>> start_turns_by_segment;
+    std::size_t touch_count = 0;
+    std::size_t touch_interior_count = 0;
+    for (auto const& item : util::enumerate(turns))
```
[the remark this answers is not in the document]
Comment (barendgehrels) [reply include/boost/geometry/algorithms/detail/overlay/discard_duplicate_turns.hpp:221]: ✅

File: doc/release_notes.qbk (hunk 3 above)
Comment (barendgehrels) [reply doc/release_notes.qbk:24]: @vissarion , I updated to 1.88 yesterday but the branch is open again for bug fixes.
So this one can probably make it.
One other PR will follow today, I'll make a separate commit and add that one also there, and change the date.

Also, I noticed yesterday some bugs that were not listed, I'll add them also there (I remember they were not merged in August so that is also 1.87).

Comment (vissarion) [reply doc/release_notes.qbk:24]: Thanks I will take care of the release, i.e. I will check if something is missing from the release notes of 1.87 and create a PR. We have roughly two more weeks.
