### PR TITLE
[fix] a few qbk includes were missing

### LINKED ISSUE #1309: Documentation generation is wrong
In this [page](https://www.boost.org/doc/libs/1_86_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_distance_haversine.html)
the section **See also** is missing.

That is already a long time. It was last there in [1.66](https://www.boost.org/doc/libs/1_66_0/libs/geometry/doc/html/geometry/reference/strategies/strategy_distance_haversine.html)

It is still in the source code:
```
\qbk{
[heading See also]
[link geometry.reference.algorithms.distance.distance_3_with_strategy distance (with strategy)]
}
```
But it is not picked up. In other algorithms, it is still there
For example assign_points [here](https://www.boost.org/doc/libs/1_66_0/libs/geometry/doc/html/geometry/reference/algorithms/assign/assign_points.html) and [here](https://www.boost.org/doc/libs/1_86_0/libs/geometry/doc/html/geometry/reference/algorithms/assign/assign_points.html)

Source code
```
\qbk{
[heading Notes]
[note Assign automatically clears the geometry before assigning (use append if you don't want that)]
[heading Example]
[assign_points] [assign_points_output]

[heading See also]
\* [link geometry.reference.algorithms.append append]
}

```

### PR DESCRIPTION
**Pull request by barendgehrels**
* also fixed frechet/haussdorff documentation
* removed ancient msvc support for doxygen_xml2qbk
* fixes #1309

### CODE REVIEW

File: doc/src/docutils/tools/doxygen_xml2qbk/doxygen_xml_parser.hpp [hunk 1]
```diff
@@ -390,23 +391,6 @@ static void parse_element(rapidxml::xml_node<>* node, configuration const& confi
...
-            el.qbk_markup.push_back(markup(markup_after, markup_synopsis, node->value()));
-        }
-        else if (full == ".detaileddescription.para.qbk.before.synopsis")
-        {
-            el.qbk_markup.push_back(markup(markup_before, markup_synopsis, node->value()));
-        }
-        else if (full == ".detaileddescription.para.qbk.distinguish")
-        {
-            el.additional_description = node->value();
-            boost::trim(el.additional_description);
```
Comment (barendgehrels) [inline doc/src/docutils/tools/doxygen_xml2qbk/doxygen_xml_parser.hpp:408]: This block is moved below. The actual bug was that some `.qbk` were missed because too explicit full paths.
In the past the XML was apparently a bit different, because it did work before.

File: doc/src/docutils/tools/doxygen_xml2qbk/doxygen_xml_parser.hpp [hunk 2]
```diff
@@ -458,9 +442,58 @@ static void parse_element(rapidxml::xml_node<>* node, configuration const& confi
             parse_parameter(node->first_node(), config, p);
             el.parameters.push_back(p);
         }
+        else if (boost::contains(full, ".qbk."))
+        {
```
Comment (barendgehrels) [inline doc/src/docutils/tools/doxygen_xml2qbk/doxygen_xml_parser.hpp:446]: The code below replaces the block above but is a bit safer in terms of full paths.
Also it should not handle sub nodes in some cases, to avoid duplicates.

File: include/boost/geometry/algorithms/discrete_frechet_distance.hpp [hunk 3]
```diff
@@ -225,15 +225,15 @@ struct discrete_frechet_distance<default_strategy, false>
 
 
 /*!
-\brief Calculate discrete Frechet distance between two geometries (currently
-       works for LineString-LineString) using specified strategy.
+\brief \brief_calc2{discrete Frechet distance, between} \brief_strategy
+\details \details_free_function{discrete_frechet_distance, discrete Frechet distance, between}.
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/discrete_frechet_distance.hpp:229]: This was written in heading `Behavior` but for all other functions it is different. Harmonized that and the parameters below.
Also the support is now as usual (not automatic though)

File: include/boost/geometry/algorithms/discrete_frechet_distance.hpp [hunk 4]
```diff
@@ -242,7 +242,8 @@ struct discrete_frechet_distance<default_strategy, false>
 [heading Available Strategies]
 \* [link geometry.reference.strategies.strategy_distance_pythagoras Pythagoras (cartesian)]
 \* [link geometry.reference.strategies.strategy_distance_haversine Haversine (spherical)]
-[/ \* more (currently extensions): Vincenty\, Andoyer (geographic) ]
+\* One of the geographic point to point strategies
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/discrete_frechet_distance.hpp:245]: We still should document `Vincenty` and others

File: include/boost/geometry/strategies/spherical/distance_haversine.hpp [hunk 5]
```diff
@@ -124,13 +124,6 @@ on a perfect sphere using haversine
 \tparam CalculationType \tparam_calculation
 \author Adapted from: http://williams.best.vwh.net/avform.htm
 \see http://en.wikipedia.org/wiki/Great-circle_distance
-\note (from Wiki:) The great circle distance d between two
-points with coordinates {lat1,lon1} and {lat2,lon2} is given by:
-    d=acos(sin(lat1)*sin(lat2)+cos(lat1)*cos(lat2)*cos(lon1-lon2))
-A mathematically equivalent formula, which is less subject
-    to rounding error for short distances is:
-    d=2*asin(sqrt((sin((lat1-lat2) / 2))^2
-    + cos(lat1)*cos(lat2)*(sin((lon1-lon2) / 2))^2))
```
Comment (barendgehrels) [inline include/boost/geometry/strategies/spherical/distance_haversine.hpp:133]: This was not really necessary here and gave some layout errors.

File: include/boost/geometry/strategies/spherical/distance_haversine.hpp [hunk 6]
```diff
@@ -124,13 +124,6 @@ on a perfect sphere using haversine
...
 \qbk{
 [heading See also]
 [link geometry.reference.algorithms.distance.distance_3_with_strategy distance (with strategy)]
```
Comment (barendgehrels) [inline include/boost/geometry/strategies/spherical/distance_haversine.hpp:129]: So this was the actual bug, it was missing, but it is back now.

image

File: include/boost/geometry/algorithms/discrete_hausdorff_distance.hpp [hunk 7]
```diff
@@ -314,16 +314,15 @@ struct discrete_hausdorff_distance<default_strategy, false>
...
 \tparam Geometry1 \tparam_geometry
 \tparam Geometry2 \tparam_geometry
-\tparam Strategy A type fulfilling a DistanceStrategy concept
-\param geometry1 Input geometry
-\param geometry2 Input geometry
-\param strategy Distance strategy to be used to calculate Pt-Pt distance
+\tparam Strategy \tparam_strategy{Distance}
+\param geometry1 \param_geometry
+\param geometry2 \param_geometry
+\param strategy \param_strategy{point to point distance}
```
Comment (barendgehrels) [inline include/boost/geometry/algorithms/discrete_hausdorff_distance.hpp:325]: Same as for Frechet. Now generates this doc:

image

File: doc/doxy/Doxyfile [hunk 8]
```diff
@@ -101,6 +101,7 @@ ALIASES                = qbk{1}="\xmlonly <qbk>\1</qbk> \endxmlonly" \
                          details_calc{1}="The free function \1 calculates the \1 of a geometry" \
                          details_calc2{2}="The free function \1 calculates the \2 of two geometries" \
                          details_calc2{1}="The free function \1 calculates the \1 of two geometries" \
+                         details_free_function{3}="The free function [^\1] calculates the \2 \3 two geometries" \
```
Comment (barendgehrels) [inline doc/doxy/Doxyfile:104]: The `\3` is for `between`. We can harmonize the macros later but I didn't want to make this PR too large.

File: include/boost/geometry/strategies/spherical/distance_haversine.hpp (hunk 5 above)
Comment (vissarion) [reply include/boost/geometry/strategies/spherical/distance_haversine.hpp:133]: Could we keep it as a comment?

File: include/boost/geometry/algorithms/discrete_frechet_distance.hpp (hunk 4 above)
Comment (vissarion) [reply include/boost/geometry/algorithms/discrete_frechet_distance.hpp:245]: Should we add a TODO here (although it is more general task than similarity distances)

**Review by vissarion — APPROVED** [review]
Looks good to me, thanks!

File: include/boost/geometry/algorithms/discrete_frechet_distance.hpp (hunk 4 above)
Comment (barendgehrels) [reply include/boost/geometry/algorithms/discrete_frechet_distance.hpp:245]: I'll make a separate issue for it.

File: include/boost/geometry/strategies/spherical/distance_haversine.hpp (hunk 5 above)
Comment (barendgehrels) [reply include/boost/geometry/strategies/spherical/distance_haversine.hpp:133]: ✅ Moved to where more was written about the calculation

**Comment by barendgehrels** [comment]
Issue created: https://github.com/boostorg/geometry/issues/1323
